### ISSUE TITLE
ClientError: Unspecified error is too vague

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/readinglist#123]
I've just encountered this situation using a latest master RL local server:

```
2015-02-13 19:46:34,423 DEBUG [readinglist][Dummy-2] "OPTIONS /v0/articles" 200 2 (5 ms)
2015-02-13 19:46:34,429 DEBUG [readinglist][Dummy-3] "GET /v0/articles" 401 117 (1 ms)
2015-02-13 19:46:38,286 WARNI [cornice][Dummy-4] returning a json string or array is a potential security hole, please ensure you really want to do this.
2015-02-13 19:46:38,286 DEBUG [readinglist][Dummy-4] "OPTIONS /v0/articles" 200 2 (1 ms)
2015-02-13 19:46:38,304 DEBUG [readinglist][Dummy-5] "GET /v0/articles" 401 117 (0 ms)
2015-02-13 19:46:42,358 DEBUG [readinglist][Dummy-2] "GET /v0/fxa-oauth/login" 302 2 (37 ms)
2015-02-13 19:46:52,686 INFO  [requests.packages.urllib3.connectionpool][Dummy-3] Starting new HTTPS connection (1): oauth-stable.dev.lcip.org
2015-02-13 19:46:53,629 ERROR [readinglist][Dummy-3] Unspecified error
Traceback (most recent call last):
  File "/Users/niko/Sites/readinglist/readinglist/views/oauth.py", line 75, in fxa_oauth_token
    token = auth_client.trade_code(code)
  File "/Users/niko/readinglist/.venv/lib/python2.7/site-packages/PyFxA-0.0.2-py2.7.egg/fxa/oauth.py", line 45, in trade_code
    resp = self.apiclient.post(url, body)
  File "/Users/niko/readinglist/.venv/lib/python2.7/site-packages/PyFxA-0.0.2-py2.7.egg/fxa/_utils.py", line 274, in post
    return self.request("POST", url, json, **kwds)
  File "/Users/niko/readinglist/.venv/lib/python2.7/site-packages/PyFxA-0.0.2-py2.7.egg/fxa/_utils.py", line 260, in request
    raise fxa.errors.ClientError(body)
ClientError: Unspecified error
2015-02-13 19:46:53,632 DEBUG [readinglist][Dummy-3] "GET /v0/fxa-oauth/token" 400 112 (1018 ms)
```

I can't provide much more reproducible steps than just trying to authenticate using the readinglist-client, which works just fine most of the time.

**Comment by Natim** [comment]
Can you provide us with a PR of how you set up debugging for this?

**Comment by n1k0** [comment]
> Can you provide us with a PR of how you set up debugging for this?

You provided me with the debug utilities on IRC :D I removed the code since, but that was basically enabling debug mode for the `http` and `requests` module, plus enabling DEBUG level for the `logging` one.

**Comment by Natim** [comment]
Duplicate of #70
