### ISSUE TITLE
No handlers could be found for logger "cliquet"

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/readinglist#163]
### Steps to reproduce:

I have two Terminal windows open:
- The first one is running `$ make serve` and is serving on http://0.0.0.0:8000
- The second one I ran `$ make loadtest-check` and got the following output:

```sh
$ make loadtest-check
.venv/bin/pserve loadtests/server.ini > readinglist.log & PID=$! && \
	  rm readinglist.log || cat readinglist.log; \
	  sleep 1 && cd loadtests && \
	  make test SERVER_URL=http://127.0.0.1:8000; \
	  EXIT_CODE=$?; kill $PID; exit $EXIT_CODE

No handlers could be found for logger "cliquet"
Traceback (most recent call last):
  File ".venv/bin/pserve", line 11, in <module>
    sys.exit(main())
  File "/Users/pdehaan/dev/github/readinglist/.venv/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 58, in main
    return command.run()
  File "/Users/pdehaan/dev/github/readinglist/.venv/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 328, in run
    global_conf=vars)
  File "/Users/pdehaan/dev/github/readinglist/.venv/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 363, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/Users/pdehaan/dev/github/readinglist/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/Users/pdehaan/dev/github/readinglist/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/Users/pdehaan/dev/github/readinglist/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/Users/pdehaan/dev/github/readinglist/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/Users/pdehaan/dev/github/readinglist/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/Users/pdehaan/dev/github/readinglist/readinglist/__init__.py", line 19, in main
    initialize_cliquet(config, version=__version__)
  File "/Users/pdehaan/dev/github/readinglist/.venv/lib/python2.7/site-packages/cliquet/__init__.py", line 192, in initialize_cliquet
    config.include("cliquet", route_prefix=api_version)
  File "/Users/pdehaan/dev/github/readinglist/.venv/lib/python2.7/site-packages/pyramid/config/__init__.py", line 755, in include
    c(configurator)
  File "/Users/pdehaan/dev/github/readinglist/.venv/lib/python2.7/site-packages/cliquet/__init__.py", line 168, in includeme
    config.registry.storage = storage.load_from_config(config)
  File "/Users/pdehaan/dev/github/readinglist/.venv/lib/python2.7/site-packages/cliquet/storage/postgresql/__init__.py", line 571, in load_from_config
    return PostgreSQL(max_fetch_size=int(max_fetch_size), **conn_kwargs)
  File "/Users/pdehaan/dev/github/readinglist/.venv/lib/python2.7/site-packages/cliquet/storage/postgresql/__init__.py", line 49, in __init__
    self._init_schema()
  File "/Users/pdehaan/dev/github/readinglist/.venv/lib/python2.7/site-packages/cliquet/storage/postgresql/__init__.py", line 95, in _init_schema
    with self.connect() as cursor:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/pdehaan/dev/github/readinglist/.venv/lib/python2.7/site-packages/cliquet/storage/postgresql/__init__.py", line 75, in connect
    raise httpexceptions.HTTPServiceUnavailable()
pyramid.httpexceptions.HTTPServiceUnavailable: The server is currently unavailable. Please try again at a later time.
.venv/bin/loads-runner --config=./config/test.ini --server-url=http://127.0.0.1:8000 loadtest.TestBasic.test_all
[========================================================================] 100%
Duration: 6.07 seconds
Hits: 813
Started: 2015-03-12 23:48:52.892783
Approximate Average RPS: 133
Average request time: 0.01s
Opened web sockets: 0
Bytes received via web sockets : 0

Success: 300
Errors: 0
Failures: 0


Slowest URL: http://127.0.0.1:8000/v1/articles/d6710ce25fbc4fd79b1aff43f92c25d8	Average Request Time: 0.043295

Stats by URLs (10 slowests):
- http://127.0.0.1:8000/v1/articles/d6710ce25fbc4fd79b1aff43f92c25d8	Average request time: 0.043295	Hits success rate: 1.0
- http://127.0.0.1:8000/v1/articles/6e7a95a3500f451ba3463a407b11612f	Average request time: 0.039359	Hits success rate: 1.0
- http://127.0.0.1:8000/v1/articles/4e09996ca8de41cf9f27972ad66e82d9	Average request time: 0.0383515	Hits success rate: 1.0
- http://127.0.0.1:8000/v1/articles/d0ad85a13ebd4799b2d31b7e893f8210	Average request time: 0.0373575	Hits success rate: 1.0
- http://127.0.0.1:8000/v1/articles/ed5a5eb72dda40539066c5a9964389a9	Average request time: 0.0358625	Hits success rate: 1.0
- http://127.0.0.1:8000/v1/articles/ac90d1356662462993834210cf602bda	Average request time: 0.0336	Hits success rate: 1.0
- http://127.0.0.1:8000/v1/articles/4dbf8193f3f64ade81c6de8eeae1b792	Average request time: 0.032587	Hits success rate: 1.0
- http://127.0.0.1:8000/v1/articles/038fbe810508467eadfd9164d28ca9d7	Average request time: 0.03205	Hits success rate: 1.0
- http://127.0.0.1:8000/v1/articles/d0603d39ab3944ccab17938ce969a4d6	Average request time: 0.0307375	Hits success rate: 1.0
- http://127.0.0.1:8000/v1/articles/ba810618690247169d0b2ff46efb4aa7	Average request time: 0.029444	Hits success rate: 1.0

Custom metrics:
- 409 : 5
- list_deleted : 19
- read_further : 48
- 200 : 144
- mark_as_read : 19
- create : 15
- update_conflict : 5
- list_archived : 18
- update : 21
- filter_sort : 34
- archive : 12
- create_conflict : 5
- 201 : 141
- update-conflict : 5
- list_continuated_pagination : 51
- poll_changes : 48
- delete : 5
/bin/sh: line 0: kill: (11475) - No such process
```

Not sure if I have a bad config or something I'm missing. Also semi-weird is the last line:

> /bin/sh: line 0: kill: (11475) - No such process

**Comment by Natim** [comment]
Well the ``make loadtest`` command already start the server so if you have started it by hand before it is normal that it couldn't stop the server since it didn't start (because already started)

If you want to start loadtest, you probably want to use the Makefile in the loadtest folder. The command you were using is the one for travis-ci to check loadtest on a github push basis.

**Comment by tarekziade** [comment]
We've hit this problem with a postgres configuration issue: the error was not showing because the cliquet logger is not configured by default. doign a PR
