### ISSUE TITLE
cannot cast type timestamp without time zone to bigint

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/readinglist#194]
Schema trouble in postgres

```sh
Mar 18 10:17:42 localhost uwsgi: SELECT resource_timestamp('toto', 'article')::BIGINT
Mar 18 10:17:42 localhost uwsgi: AS timestamp;
Mar 18 10:17:42 localhost uwsgi: cannot cast type timestamp without time zone to bigint
Mar 18 10:17:42 localhost uwsgi: LINE 2:         SELECT resource_timestamp('toto', 'article')::BIGINT
Mar 18 10:17:42 localhost uwsgi: ^
Mar 18 10:17:42 localhost uwsgi: Traceback (most recent call last):
Mar 18 10:17:42 localhost uwsgi: File "/data/readinglist/lib/python2.7/site-packages/cliquet-1.2.dev2-py2.7.egg/cliquet/storage/postgresql/__init__.py", line 43, in connect
Mar 18 10:17:42 localhost uwsgi: yield cursor
Mar 18 10:17:42 localhost uwsgi: File "/data/readinglist/lib/python2.7/site-packages/cliquet-1.2.dev2-py2.7.egg/cliquet/storage/postgresql/__init__.py", line 156, in collection_timestamp
Mar 18 10:17:42 localhost uwsgi: cursor.execute(query, placeholders)
Mar 18 10:17:42 localhost uwsgi: File "/data/readinglist/lib/python2.7/site-packages/psycopg2-2.6-py2.7-linux-x86_64.egg/psycopg2/extras.py", line 120, in execute
Mar 18 10:17:42 localhost uwsgi: return super(DictCursor, self).execute(query, vars)
Mar 18 10:17:42 localhost uwsgi: ProgrammingError: cannot cast type timestamp without time zone to bigint
Mar 18 10:17:42 localhost uwsgi: LINE 2:         SELECT resource_timestamp('toto', 'article')::BIGINT
Mar 18 10:17:42 localhost uwsgi: ^
Mar 18 10:17:42 localhost uwsgi: cannot cast type timestamp without time zone to bigint
Mar 18 10:17:42 localhost uwsgi: LINE 2:         SELECT resource_timestamp('toto', 'article')::BIGINT
Mar 18 10:17:42 localhost uwsgi: ^
Mar 18 10:17:42 localhost uwsgi: Traceback (most recent call last):
Mar 18 10:17:42 localhost uwsgi: File "/data/readinglist/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
Mar 18 10:17:42 localhost uwsgi: response = handler(request)
Mar 18 10:17:42 localhost uwsgi: File "/data/readinglist/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
Mar 18 10:17:42 localhost uwsgi: response = view_callable(context, request)
Mar 18 10:17:42 localhost uwsgi: File "/data/readinglist/lib/python2.7/site-packages/pyramid/config/views.py", line 596, in __call__
Mar 18 10:17:42 localhost uwsgi: return view(context, request)
Mar 18 10:17:42 localhost uwsgi: File "/data/readinglist/lib/python2.7/site-packages/pyramid/config/views.py", line 329, in attr_view
Mar 18 10:17:42 localhost uwsgi: return view(context, request)
Mar 18 10:17:42 localhost uwsgi: File "/data/readinglist/lib/python2.7/site-packages/pyramid/config/views.py", line 305, in predicate_wrapper
Mar 18 10:17:42 localhost uwsgi: return view(context, request)
Mar 18 10:17:42 localhost uwsgi: File "/data/readinglist/lib/python2.7/site-packages/pyramid/config/views.py", line 245, in _secured_view
Mar 18 10:17:42 localhost uwsgi: return view(context, request)
Mar 18 10:17:42 localhost uwsgi: File "/data/readinglist/lib/python2.7/site-packages/pyramid/config/views.py", line 355, in rendered_view
Mar 18 10:17:42 localhost uwsgi: result = view(context, request)
Mar 18 10:17:42 localhost uwsgi: File "/data/readinglist/lib/python2.7/site-packages/pyramid/config/views.py", line 501, in _requestonly_view
Mar 18 10:17:42 localhost uwsgi: response = view(request)
Mar 18 10:17:42 localhost uwsgi: File "/data/readinglist/lib/python2.7/site-packages/cornice-0.19.0-py2.7.egg/cornice/service.py", line 497, in wrapper
Mar 18 10:17:42 localhost uwsgi: ob = args['klass'](**params)
Mar 18 10:17:42 localhost uwsgi: File "/data/readinglist/lib/python2.7/site-packages/cliquet-1.2.dev2-py2.7.egg/cliquet/resource.py", line 63, in __init__
Mar 18 10:17:42 localhost uwsgi: self.timestamp = self.db.collection_timestamp(**self.db_kwargs)
Mar 18 10:17:42 localhost uwsgi: File "/data/readinglist/lib/python2.7/site-packages/cliquet-1.2.dev2-py2.7.egg/cliquet/storage/postgresql/__init__.py", line 157, in collection_timestamp
Mar 18 10:17:42 localhost uwsgi: result = cursor.fetchone()
Mar 18 10:17:42 localhost uwsgi: File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
Mar 18 10:17:42 localhost uwsgi: self.gen.throw(type, value, traceback)
Mar 18 10:17:42 localhost uwsgi: File "/data/readinglist/lib/python2.7/site-packages/cliquet-1.2.dev2-py2.7.egg/cliquet/storage/postgresql/__init__.py", line 51, in connect
Mar 18 10:17:42 localhost uwsgi: raise exceptions.BackendError(original=e)
Mar 18 10:17:42 localhost uwsgi: BackendError
```

**Comment by ametaireau** [comment]
[schema.sql](https://github.com/mozilla-services/cliquet/blob/master/cliquet/storage/postgresql/schema.sql) contains information on how to cast the timetamps to integers, in the [as_epoch](https://github.com/mozilla-services/cliquet/blob/master/cliquet/storage/postgresql/schema.sql#L20-L28) function.

The cast need to be installed as the postgres super user, and apparently, what this stack trace is telling us is that the cast doesn't exist and as such cannot be done.

I'm looking with @micheletto to see why we're seing this.

**Comment by leplatrem** [comment]
We got rid of this in cliquet 1.2.1, thus readinglist 1.1.0.

**Comment by stephendonner** [comment]
For cross-reference, see https://bugzilla.mozilla.org/show_bug.cgi?id=1141155#c10
