### ISSUE TITLE
Do not break on double encoded json

### ISSUE THREAD

**Issue by ametaireau** [mozilla-services/readinglist#90]
Sometimes, the server breaks with some bad JSON:

Add this in the `JSON_BREAKER` file:

```
"{\"title\":\"a\",\"url\":\"b\",\"added_by\":\"c\"}"
```

Then send a request with HTTPie:

```bash
cat JSON_BREAKER | http POST http://0.0.0.0:8000/v0/articles --auth toto:toto
```

We get an error in response:

```
Traceback (most recent call last):
  File "/home/alexis/dev/github.com/readinglist/.venv/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/alexis/dev/github.com/readinglist/.venv/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/alexis/dev/github.com/readinglist/.venv/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 596, in __call__
    return view(context, request)
  File "/home/alexis/dev/github.com/readinglist/.venv/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/home/alexis/dev/github.com/readinglist/.venv/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/home/alexis/dev/github.com/readinglist/.venv/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
  File "/home/alexis/dev/github.com/readinglist/.venv/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/home/alexis/dev/github.com/readinglist/.venv/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/home/alexis/dev/github.com/readinglist/.venv/local/lib/python2.7/site-packages/cornice-0.17-py2.7.egg/cornice/service.py", line 497, in wrapper
    validate_colander_schema(ob.schema, request)
  File "/home/alexis/dev/github.com/readinglist/.venv/local/lib/python2.7/site-packages/cornice-0.17-py2.7.egg/cornice/schemas.py", line 146, in validate_colander_schema
    _validate_fields('body', body)
  File "/home/alexis/dev/github.com/readinglist/.venv/local/lib/python2.7/site-packages/cornice-0.17-py2.7.egg/cornice/schemas.py", line 98, in _validate_fields
    data = webob.multidict.MultiDict(schema.unflatten(data))
  File "/home/alexis/dev/github.com/readinglist/.venv/local/lib/python2.7/site-packages/cornice-0.17-py2.7.egg/cornice/schemas.py", line 80, in unflatten
    return self.colander_schema.unflatten(data)
  File "/home/alexis/dev/github.com/readinglist/.venv/local/lib/python2.7/site-packages/colander-1.0-py2.7.egg/colander/__init__.py", line 1884, in unflatten
    paths = sorted(fstruct.keys())
AttributeError: 'str' object has no attribute 'keys'

```

**Comment by leplatrem** [comment]
I see no readinglist in the stacktrace, meaning that we will rather have to fix it in Cornice !

**Comment by leplatrem** [comment]
Nhttp://mattryall.net/blog/2008/03/default-content-type

**Comment by Natim** [comment]
Refs https://github.com/mozilla-services/cornice/pull/271
