### ISSUE TITLE
Delete should increment last-modified on collection

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/readinglist#95]
http://pastebin.mozilla.org/8562034

**Comment by Natim** [comment]
Refs #41

**Comment by leplatrem** [comment]
Good news so far, I reproduce in a test 

```
✗ nosetests -s readinglist.tests.test_backend
...............F.........................F...........
======================================================================
FAIL: test_timestamp_are_incremented_on_delete (readinglist.tests.test_backend.MemoryBackendTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mathieu/Code/Mozilla/readinglist/readinglist/tests/test_backend.py", line 180, in test_timestamp_are_incremented_on_delete
    self.assertTrue(before < after)
AssertionError: False is not true

======================================================================
FAIL: test_timestamp_are_incremented_on_delete (readinglist.tests.test_backend.RedisBackendTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mathieu/Code/Mozilla/readinglist/readinglist/tests/test_backend.py", line 180, in test_timestamp_are_incremented_on_delete
    self.assertTrue(before < after)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 53 tests in 0.197s

```
